### ISSUE TITLE
Spline Fences does not bend

### ISSUE THREAD

**Issue by kae1616** [skxdoom/UE4-PHISMTools#2]
The meshes do not bend according to the spline. Or is it that this function is not applicable yet since its stated WIP? The meshes do follow the spline angle but do not bend. One example is the use of typical pipings/fences, there are gaps in between the mesh when the spline is bent, the solution is for the meshes to bend along with the spline, not sure if this will mess up the UV's mapping though.

I found a similar solution here, https://www.youtube.com/watch?v=7YUxM0NDWRY

Thanks!

**Comment by skxdoom** [comment]
Yes, BP_Spline_Fences is the most unfinished one. In real life fences don't really bend, so I didn't come up with single solution back then. Sorry for inconvenience, but the whole system is provided to public as-is due to time constraints, I probably should've clarify that.

I'm also not so sure that HISM (Hierarchical Instanced Static Meshes) are so important anymore, since UE4.22 Epic developed auto-instancing for usual Static Meshes (yet they were absolutely needed for a UE4.19 open world game I worked on), so it itn't a bottleneck anymore. And HISM have some limitations for itself - for example they just don't support static lighting.

I hope you understand me, because in earlier versions of Unreal the count of meshes could be a huge problem and the system was developed to overcome this and now it's not so needed anymore.

Anyway, I got too technical, so the short answer is: you probably need a custom solution either built based on PHISM Tools or from scratch.

**Comment by kae1616** [comment]
not really sure about auto instancing since duplicating static meshes always gave me massive drop in fps after replicating it several times ( high draw calls ). your tool is really good and it gave me a huge fps advantage working with my projects. ( im on 4.24 now )

and no worries, i just want to say thanks for releasing such a good tool to the public, wish you all the best for your future projects!

**Comment by skxdoom** [comment]
That's really good to know, thank you very much! Considering all last Unreal updates I might redone the whole tool someday, maybe, so it could get more performant and more user friendly.
